### ISSUE TITLE
Как уменьшить размер прошивки для ATTiny85?

### ISSUE THREAD

**Issue by dmikushin** [GyverLibs/GyverINA#5]
Прошивка, использующая GyverINA на ATTiny85 не вмещается в доступную память. Безуспешно перебирая флаги компилятора, обнаружил что `#pragma GCC optimize("fast-math")` чудесным образом делает прошивку меньше, и только тогда она вмещается. Но всё равно получается контроллер, управляющий единственной функцией, довольно бестолково. В чём прикол, почему GyverINA такая большая, и как посоветуете её уменьшить?

**Comment by GyverLibs** [comment]
Скорее всего много жрет встроенная библиотека Wire, ну и float вычисления. Сама библиотека очень компактная

**Comment by dmikushin** [comment]
Спасибо, становится понятно почему именно `#pragma GCC optimize("fast-math")` исправляет ситуацию в какой-то мере. Что-то можно отрезать от Wire? Нам ведь нужен только I2C, верно?

**Comment by GyverLibs** [comment]
Ну wire и есть i2c

**Comment by dmikushin** [comment]
Ясно. Но Вас-то не удивляет, что переферийная библиотека в одинчку забивает всю память чипа? Это же комично, как минимум.

**Comment by GyverLibs** [comment]
Комично, поэтому я сел скомпилил. Встроенные примеры занимают 56% и 57% памяти, а если убрать из кода Serial - то 33% и 34%. Думаю вопрос снят, разбирайтесь что у вас не так
![image](https://github.com/GyverLibs/GyverINA/assets/84599917/142ec1d0-e3ee-4ce4-ad86-4de240e4998b)

**Comment by dmikushin** [comment]
Вот для сравнения: 99%. Ещё только два хедера дополнительно к GyverINA:

![Screenshot from 2023-08-25 00-13-35](https://github.com/GyverLibs/GyverINA/assets/5672874/ad1f2172-351a-4af3-886b-7f1e70eb8ef9)

**Comment by GyverLibs** [comment]
значит все вопросы к хэдерам

**Comment by dmikushin** [comment]
Спасибо большое за анализ! Простите за последний вопрос: какая у вас версия Arduino IDE?

**Comment by GyverLibs** [comment]
IDE v1.8.19, ядро [ATTinyCore](https://github.com/SpenceKonde/ATTinyCore) v1.5.2
